"use client";
import {useEffect,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {MapPinned,Plane,Users,CloudSun,ListChecks,ShieldCheck,LogOut,Plus,Download,Save} from "lucide-react";
import {LiveMap} from "@/components/live-map";
import {Ledger} from "@/components/journey-ledger";
import {MembersEditor,StopEditor} from "@/components/journey-editors";
import {defaultTrip,type TripSnapshot,type TravelStop,type TransportPlan,type TripReminder} from "@/lib/trip-data";
import {parseImport} from "@/lib/travel-schema";
import {amapUrl,googleUrl,receiptFile,saveFile} from "@/lib/navigation";
import {downloadGuide,printGuide} from "@/lib/offline-guide";
import {scheduleWarnings} from "@/lib/schedule";
import "./journey.css";
type P={view:boolean;manage:boolean;edit:boolean;ledger:boolean;memberId:string|null};
type J={id:string;revision:string;permissions:P;trip:TripSnapshot};
type Api = {error?:string;journeys:J[];owner:boolean;user:{id:string;email:string;name:string};revision:string;trip:TripSnapshot;id:string;code:string;expires:string};
type Weather={days:{date:string;max:number;min:number;rain:number}[]};
const modes=["飞机","火车","KTX","地铁","公交","机场交通","出租车","自驾","轮渡","步行"] as const;
function emptyTrip():TripSnapshot{return {...structuredClone(defaultTrip),title:"新的旅行",monthRange:"日期待定",exactStart:"",exactEnd:"",members:[],days:[{no:"01",title:"抵达目的地",city:"",summary:"",stops:[]}],transports:[],preTripReminders:[],notes:"",budget:[],ledger:{baseCurrency:"CNY",bills:[],repayments:[]},history:[]};}
export default function Home(){
 const [journeys,setJourneys]=useState<J[]>([]),[selected,setSelected]=useState(""),[trip,setTrip]=useState<TripSnapshot|null>(null);
 const [owner,setOwner]=useState(false),[user,setUser]=useState({id:"",email:"",name:""}),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const [tab,setTab]=useState("overview"),[dialog,setDialog]=useState<"members"|"weather"|"reminders"|"new"|"import"|"world"|null>(null);
 const [stopEdit,setStopEdit]=useState<{day:number;index:number;stop:TravelStop}|null>(null);
 const [imported,setImported]=useState<TripSnapshot|null>(null),[newTitle,setNewTitle]=useState(""),[newCity,setNewCity]=useState(""),[newDays,setNewDays]=useState(5),[newMonth,setNewMonth]=useState("");
 const [reminders,setReminders]=useState<TripReminder[]>([]),[newReminder,setNewReminder]=useState(""),[reminderScope,setReminderScope]=useState("common");
 const [weatherPoint,setWeatherPoint]=useState(0),[weather,setWeather]=useState<Weather|null>(null),[weatherStatus,setWeatherStatus]=useState("");
 const current=journeys.find(j=>j.id===selected),p=current?.permissions;
 const state=useRef({selected,trip,current,dirty});state.current={selected,trip,current,dirty};
 const lock=useRef(false),drag=useRef<{day:number;index:number}|null>(null);
 async function load(id?:string){
  setLoading(true);
  try{const response=await fetch("/api/journeys");if(response.status===401){location.href="/login";return;}
   const data=await response.json() as Api;if(!response.ok)throw new Error(data.error);
   setJourneys(data.journeys);setOwner(data.owner);setUser(data.user);
   const chosen=data.journeys.find((j:J)=>j.id===(id||state.current.selected))||data.journeys[0];
   setSelected(chosen?.id||"");setTrip(chosen?structuredClone(chosen.trip):null);setDirty(false);
  }catch(e){setNotice((e as Error).message);}finally{setLoading(false);}
 }
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const timer=setInterval(async()=>{
  const s=state.current;if(!s.selected||lock.current)return;
  try{const r=await fetch("/api/journeys?id="+encodeURIComponent(s.selected));
   if(r.status===403){setTrip(null);setJourneys(js=>js.filter(j=>j.id!==s.selected));setNotice("你对这次旅行的访问权限已被移除。");return;}
   if(!r.ok)return;const data=await r.json() as Api;const fresh=data.journeys?.[0] as J;
   if(fresh&&fresh.revision!==s.current?.revision){
    if(s.dirty||dialog||stopEdit){setNotice("其他成员有更新。请先保存或下载草稿，再重新载入。");}
    else{setJourneys(js=>js.map(j=>j.id===fresh.id?fresh:j));setTrip(structuredClone(fresh.trip));}
   }
  }catch{/* retain visible snapshot while offline */}
 },30000);return()=>clearInterval(timer);},[dialog,stopEdit]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(state.current.dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f);},[]);
 function patch(change:Partial<TripSnapshot>){setTrip(t=>t?{...t,...change}:t);setDirty(true);}
 async function mutate(action:string,values:Record<string,unknown>={}):Promise<boolean>{
  if(lock.current)return false;const s=state.current;if(!s.current||!s.trip)return false;
  if(s.dirty&&action!=="plan"){setNotice("请先保存行程草稿，再修改成员、账本或提醒。");return false;}
  lock.current=true;setBusy(true);
  try{const r=await fetch("/api/journeys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id:s.selected,revision:s.current.revision,...values})});
   const data=await r.json() as Api;if(!r.ok)throw new Error(data.error);
   setJourneys(js=>js.map(j=>j.id===s.selected?{...j,revision:data.revision,trip:data.trip}:j));setTrip(data.trip);setDirty(false);setNotice("已保存并同步。");return true;
  }catch(e){setNotice((e as Error).message);return false;}finally{lock.current=false;setBusy(false);}
 }
 async function create(t?:TripSnapshot,seed=false){setBusy(true);try{const r=await fetch("/api/journeys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",trip:t,seed})});const d=await r.json() as Api;if(!r.ok)throw new Error(d.error);setDialog(null);setImported(null);await load(d.id);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 function changeDay(i:number,change:Partial<TripSnapshot["days"][number]>){if(trip)patch({days:trip.days.map((d,n)=>n===i?{...d,...change}:d)});}
 function moveStop(from:number,index:number,to:number,position:number){if(!trip)return;const days=structuredClone(trip.days);const [s]=days[from].stops.splice(index,1);days[to].stops.splice(position,0,s);patch({days});}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice("已复制。");}catch{setNotice("复制失败，请长按文字手动复制："+text);}}
 function dayDate(index:number){if(!trip?.exactStart)return "日期待定";const date=new Date(trip.exactStart+"T12:00:00Z");date.setUTCDate(date.getUTCDate()+index);return date.toISOString().slice(0,10);}
 const points=trip?.days.flatMap(d=>d.stops).filter(s=>s.location)||[];
 useEffect(()=>{if(dialog!=="weather")return;const point=points[weatherPoint]||points[0];if(!point?.location){setWeatherStatus("请先为行程地点填写坐标。");return;}const controller=new AbortController();setWeather(null);setWeatherStatus("正在读取近期天气…");
 void fetch("/api/weather?"+new URLSearchParams({lat:String(point.location.lat),lng:String(point.location.lng),name:point.title}),{signal:controller.signal}).then(async r=>{const d=await r.json() as Api;if(!r.ok)throw new Error(d.error);setWeather(d as unknown as Weather);setWeatherStatus("");}).catch(e=>{if(!controller.signal.aborted)setWeatherStatus(e.message);});return()=>controller.abort();
 },[dialog,weatherPoint,selected]);
 async function recovery(){try{const r=await fetch("/api/auth/recovery",{method:"POST"});const d=await r.json() as Api;if(!r.ok)throw new Error(d.error);saveFile("创建者恢复码.txt",`账号：${user.email}\n恢复码：${d.code}\n有效期至：${d.expires}\n在登录页“重置”中使用。仅能使用一次，请私下保存。\n`,"text/plain;charset=utf-8");setNotice("恢复码已下载，请私下保存；重新生成会使旧码失效。");}catch(e){setNotice((e as Error).message);}}
 function openDialog(v:typeof dialog){if(dirty&&v!=="weather"){setNotice("请先保存行程草稿。");return;}if(v==="reminders")setReminders(structuredClone(trip?.preTripReminders||[]));setDialog(v);}
 if(loading&&!trip)return <main className="journey-app"><p className="empty">正在载入旅行…</p>{notice&&<p>{notice}</p>}</main>;
 return <main className="journey-app"><header className="journey-top"><a href="/" className="brand"><MapPinned size={24}/><span>私人旅行档案</span></a><div className="row wrap"><span className="muted user-label">{user.name}</span>{owner&&<a className="plain-button" href="/admin"><ShieldCheck size={17}/>后台</a>}<Button variant="ghost" aria-label="退出登录" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/login";}}><LogOut size={18}/></Button></div></header>
 <div className="journey-container"><div className="toolbar row between wrap"><div className="row wrap"><select aria-label="选择旅行" disabled={dirty} value={selected} onChange={e=>{const j=journeys.find(j=>j.id===e.target.value);setSelected(e.target.value);setTrip(j?structuredClone(j.trip):null);setTab("overview");}}>{!journeys.length&&<option value="">暂无旅行</option>}{journeys.map(j=><option value={j.id} key={j.id}>{j.trip.title}</option>)}</select>{owner&&<><Button variant="outline" onClick={()=>openDialog("new")}><Plus size={16}/>新旅行</Button><Button variant="outline" onClick={()=>openDialog("import")}>导入方案</Button><Button variant="ghost" onClick={()=>openDialog("world")}>私人足迹地图</Button></>}</div>{trip&&<div className="row wrap"><Button variant="outline" onClick={()=>downloadGuide(trip)}><Download size={16}/>离线 HTML</Button><Button variant="outline" onClick={()=>{try{printGuide(trip);}catch(e){setNotice((e as Error).message);}}}>保存 PDF</Button></div>}</div>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice("")}>×</button></div>}
 {!trip?<section className="travel-card empty"><h1>你的下一段旅行</h1><p>{owner?"新建旅行、导入对话生成的方案，或载入首尔釜山案例。":"注册成功。请将账号邮箱告诉旅行创建者，批准加入后，这里会显示对应旅行。"}</p>{owner&&<Button disabled={busy} onClick={()=>void create(undefined,true)}>载入首尔 · 釜山案例</Button>}<Button variant="outline" onClick={()=>void load()}>刷新旅行列表</Button></section>:<>
 <section className="flight-strip">{trip.transports.filter(t=>t.type==="飞机").map(t=><article key={t.id}><Plane size={20}/><div><strong>{t.from} → {t.to}</strong><p>{t.date||"日期待定"} · {t.service||"班次待定"}</p><p className="muted">{t.detail}</p></div></article>)}{!trip.transports.some(t=>t.type==="飞机")&&<p>尚未添加航班，可在交通中自由录入。</p>}</section>
 <section className="journey-hero"><p className="eyebrow">YOUR JOURNEY · {trip.days.length} DAYS</p>{p?.edit?<Input aria-label="旅行标题" className="journey-title" value={trip.title} onChange={e=>patch({title:e.target.value})}/>:<h1 className="journey-title">{trip.title}</h1>}<div className="fields"><label>暂定月份<Input disabled={!p?.edit} value={trip.monthRange} onChange={e=>patch({monthRange:e.target.value})}/></label><label>出发日期<Input disabled={!p?.edit} type="date" value={trip.exactStart} onChange={e=>{const start=e.target.value;const d=new Date(start+"T12:00:00Z");if(start)d.setUTCDate(d.getUTCDate()+trip.days.length-1);patch({exactStart:start,exactEnd:start?d.toISOString().slice(0,10):""});}}/></label><label>返回日期<Input disabled={!p?.edit} type="date" value={trip.exactEnd} onChange={e=>patch({exactEnd:e.target.value})}/></label></div></section>
 <div className="quick-cards"><button onClick={()=>openDialog("members")}><Users/><strong>同行成员</strong><span>{trip.members.filter(m=>!m.archived).length} 人 · 查看与管理</span></button><button onClick={()=>openDialog("weather")}><CloudSun/><strong>季节与天气</strong><span>目的地近 7 天天气</span></button><button onClick={()=>openDialog("reminders")}><ListChecks/><strong>出发前提醒</strong><span>{trip.preTripReminders.filter(r=>r.done).length} / {trip.preTripReminders.length} 已完成</span></button></div>
 <nav className="journey-tabs">{[["overview","总览"],["days","每日行程"],["transport","交通"],["ledger","记账分账"],["history","修改记录"]].map(([id,label])=><button key={id} aria-current={tab===id?"page":undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="overview"&&trip.days.some(d=>/首尔|釜山/.test(d.city))&&<img src="/images/korea-pixel-panorama.png" alt="首尔与釜山的冬季像素风装饰" style={{width:"100%",maxHeight:180,objectFit:"contain",margin:"12px 0"}}/>}
 {scheduleWarnings(trip).map((w,i)=><p className="notice" key={i}>{w}</p>)}
 {tab==="overview"&&<section className="travel-card"><p className="eyebrow">THE WHOLE JOURNEY</p><h2>本次旅程</h2><LiveMap days={trip.days}/><div className="day-summary">{trip.days.map((d,i)=><button className="inset" key={i} onClick={()=>setTab("days")}><span className="eyebrow">DAY {i+1}</span><h3>{d.city||"目的地待定"}</h3><p>{d.title}</p><p className="muted">{dayDate(i)}</p></button>)}</div></section>}
 {tab==="days"&&<div className="stack">{trip.days.map((day,di)=><section className="travel-card" key={di} onDragOver={e=>{if(p?.edit)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(drag.current&&p?.edit){moveStop(drag.current.day,drag.current.index,di,day.stops.length);drag.current=null;}}}><div className="row between wrap"><h2>第 {di+1} 天 · {day.city} <small>{dayDate(di)}</small></h2>{p?.edit&&<div className="row"><Button variant="ghost" disabled={di===0} onClick={()=>{const days=[...trip.days];[days[di-1],days[di]]=[days[di],days[di-1]];patch({days});}}>上移整天</Button><Button variant="ghost" onClick={()=>{if(confirm("删除这一天及其景点？保存后生效。"))patch({days:trip.days.filter((_,i)=>i!==di)});}}>删除这天</Button></div>}</div>
 {p?.edit?<div className="fields"><label>城市<Input value={day.city} onChange={e=>changeDay(di,{city:e.target.value})}/></label><label>当天主题<Input value={day.title} onChange={e=>changeDay(di,{title:e.target.value})}/></label><label>摘要<Input value={day.summary} onChange={e=>changeDay(di,{summary:e.target.value})}/></label></div>:<p>{day.title} · {day.summary}</p>}
 {day.stops.map((s,si)=><article key={si} className="stop-row" draggable={!!p?.edit} onDragStart={()=>{drag.current={day:di,index:si};}} onDrop={e=>{if(drag.current&&p?.edit){e.stopPropagation();moveStop(drag.current.day,drag.current.index,di,si);drag.current=null;}}}><div className="stop-number">{si+1}</div><div className="stop-body"><p className="eyebrow">{s.time} · {s.kind}</p><h3>{s.title}</h3><p>{s.note}</p><p className="muted">{s.transportFromPrevious}</p>{s.nativeName&&<p lang="und">{s.nativeName}</p>}{s.address&&<p>{s.address}</p>}{s.openingHours&&<p>开放：{s.openingHours} · 停留 {s.durationMinutes||"待定"} 分钟</p>}{s.ticketRequired&&<label className="check ticket"><input type="checkbox" checked={!!s.ticketDone} disabled={!p?.edit} onChange={e=>changeDay(di,{stops:day.stops.map((v,i)=>i===si?{...v,ticketDone:e.target.checked}:v)})}/>{s.ticketDone?"已购票 / 预约":"需要购票 / 预约"} · {s.ticketNote}</label>}<div className="row wrap"><a className="plain-button" href={googleUrl(s)} target="_blank" rel="noreferrer">Google 导航 ↗</a><a className="plain-button" href={amapUrl(s)} target="_blank" rel="noreferrer">高德地图 ↗</a><Button variant="outline" disabled={!s.nativeName||!s.verifiedAt} onClick={()=>void copy(s.nativeName!)}>复制当地名称</Button><Button variant="outline" disabled={!s.address||!s.verifiedAt} onClick={()=>void copy(s.address!)}>复制当地地址</Button></div>{!s.verifiedAt&&<p className="muted">当地名称与地址待核实；编辑地点补充来源并确认后可复制。</p>}
 {p?.edit&&<div className="row wrap"><Button variant="ghost" onClick={()=>setStopEdit({day:di,index:si,stop:structuredClone(s)})}>编辑地点</Button><Button variant="ghost" disabled={!si} onClick={()=>moveStop(di,si,di,si-1)}>上移</Button><select aria-label="移动到另一天" value="" onChange={e=>{if(e.target.value!=="")moveStop(di,si,Number(e.target.value),trip.days[Number(e.target.value)].stops.length);}}><option value="">移动到…</option>{trip.days.map((_,i)=>i!==di&&<option key={i} value={i}>第 {i+1} 天</option>)}</select><Button variant="ghost" onClick={()=>changeDay(di,{stops:day.stops.filter((_,i)=>i!==si)})}>删除</Button></div>}</div></article>)}
 {p?.edit&&<Button variant="outline" onClick={()=>setStopEdit({day:di,index:day.stops.length,stop:{title:"新地点",time:"09:00",kind:"文化",note:""}})}>添加地点</Button>}<details><summary>查看当天真实地图</summary><LiveMap days={[day]}/></details></section>)}{p?.edit&&<Button onClick={()=>patch({days:[...trip.days,{no:String(trip.days.length+1).padStart(2,"0"),title:"新的一天",city:"",summary:"",stops:[]}]})}>增加一天</Button>}</div>}
 {tab==="transport"&&<div className="stack">{trip.transports.map((t,i)=><section className="travel-card" key={t.id}><div className="row between"><h2>{t.type} · {t.from} → {t.to}</h2>{p?.edit&&<Button variant="ghost" onClick={()=>patch({transports:trip.transports.filter((_,n)=>n!==i)})}>删除</Button>}</div><div className="fields"><label>交通工具<select disabled={!p?.edit} value={t.type} onChange={e=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,type:e.target.value as TransportPlan["type"]}:v)})}>{modes.map(m=><option key={m}>{m}</option>)}</select></label>{([["from","出发地"],["to","到达地"],["date","出发当地日期时间"],["arrival","到达当地日期时间"],["departureTimezone","出发时区，如 Asia/Shanghai"],["arrivalTimezone","到达时区，如 Asia/Seoul"],["service","航班 / 车次 / 线路"],["terminal","航站楼 / 站台"],["seat","座位"],["baggage","行李额度"]] as const).map(([key,label])=><label key={key}>{label}<Input disabled={!p?.edit} value={t[key]||""} onChange={e=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,[key]:e.target.value}:v)})}/></label>)}</div><label>详细说明<Textarea disabled={!p?.edit} value={t.detail} onChange={e=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,detail:e.target.value}:v)})}/></label><p>本段同行人员</p><div className="row wrap">{trip.members.filter(m=>!m.archived).map(m=><label className="check" key={m.id}><input disabled={!p?.edit} type="checkbox" checked={t.memberIds?.includes(m.id)||false} onChange={e=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,memberIds:e.target.checked?[...(v.memberIds||[]),m.id]:(v.memberIds||[]).filter(id=>id!==m.id)}:v)})}/>{m.name}</label>)}</div>{t.attachment&&<details><summary>查看交通附件</summary><img className="receipt" src={t.attachment} alt="交通附件"/></details>}{p?.edit&&<label>上传票据截图（同行可见）<Input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void receiptFile(f).then(attachment=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,attachment}:v)})).catch(e=>setNotice(e.message));}}/>{t.attachment&&<Button variant="ghost" onClick={()=>patch({transports:trip.transports.map((v,n)=>n===i?{...v,attachment:undefined}:v)})}>移除附件</Button>}</label>}</section>)}{p?.edit&&<Button onClick={()=>patch({transports:[...trip.transports,{id:crypto.randomUUID(),type:"飞机",status:"待确认",from:"",to:"",date:"",service:"",detail:"",departureTimezone:"Asia/Shanghai",arrivalTimezone:"Asia/Shanghai"}]})}>添加交通</Button>}</div>}
 {tab==="ledger"&&<Ledger key={selected} ledger={trip.ledger} members={trip.members} canEdit={!!p?.ledger} manager={!!p?.manage} viewerId={p?.memberId||null} onSave={ledger=>mutate("ledger",{ledger})}/>}
 {tab==="history"&&<section className="travel-card"><h2>最近修改记录</h2><p className="muted">保留最近 100 次变更摘要。个人提醒记录仅本人可见。</p>{[...(trip.history||[])].reverse().map((h,i)=><p key={i}>{h.at.replace("T"," ").slice(0,19)} · {h.actor} · {h.action.startsWith("个人提醒")?"编辑个人提醒":h.action}</p>)}</section>}
 <section className="travel-card notes"><h2>注意事项</h2><Textarea disabled={!p?.edit} value={trip.notes} onChange={e=>patch({notes:e.target.value})}/></section>
 <footer className="save-bar"><span>{dirty?"有尚未保存的行程修改":"已载入云端版本"} · 多人更新每 30 秒检查一次</span><div className="row wrap">{dirty&&<Button variant="outline" onClick={()=>saveFile("旅行草稿.json",JSON.stringify({version:1,trip},null,2))}>下载草稿</Button>}<Button variant="outline" onClick={()=>{if(!dirty||confirm("重新载入会丢弃未保存修改。已下载草稿了吗？"))void load();}}>重新载入</Button>{p?.edit&&<Button disabled={busy||!dirty} onClick={()=>void mutate("plan",{trip})}><Save size={16}/>保存行程</Button>}</div></footer>
 </>}
 {owner&&<div className="row wrap bottom-tools"><Button variant="ghost" onClick={()=>void recovery()}>下载创建者恢复码</Button><a href="/旅行规划说明.md" download>下载对话规划说明</a><a href="/travel-import-template.json" download>下载导入模板</a></div>}
 </div>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog(null);}}><DialogContent className="travel-dialog"><DialogHeader><DialogTitle>{{members:"同行成员",weather:"季节与近期天气",reminders:"出发前提醒",new:"创建旅行",import:"导入对话方案",world:"私人旅行足迹"}[dialog||"new"]}</DialogTitle></DialogHeader>
 {notice&&<p role="status" className="notice">{notice}</p>}
 {dialog==="reminders"&&!p?.memberId&&<p>请先在同行成员中为自己绑定已注册账号，保存后重新载入，即可编辑提醒。其他人的个人提醒始终不会显示。</p>}
 {dialog==="members"&&trip&&<MembersEditor key={selected} trip={trip} journeyId={selected} manage={!!p?.manage} onSave={members=>mutate("members",{members})}/>}
 {dialog==="world"&&owner&&<><p>仅创建者可见。显示已结束旅行的地点。</p><LiveMap days={journeys.filter(j=>j.trip.exactEnd&&j.trip.exactEnd<new Date().toISOString().slice(0,10)).flatMap(j=>j.trip.days)}/></>}
 {dialog==="weather"&&<><label>查看地点<select value={weatherPoint} onChange={e=>setWeatherPoint(Number(e.target.value))}>{points.map((s,i)=><option key={i} value={i}>{s.title}</option>)}</select></label><p>以下为从今天起的 7 天预报，不代表远期出行天气。日期未确定时请在注意事项填写季节参考。</p>{weatherStatus&&<p>{weatherStatus}</p>}<div className="fields">{weather?.days.map(d=><article className="inset" key={d.date}><strong>{d.date}</strong><p>{d.min}–{d.max}℃</p><p>降雨概率 {d.rain}%</p></article>)}</div></>}
 {dialog==="reminders"&&trip&&<div className="stack">{reminders.map((n,i)=><div className="row" key={n.id}><input aria-label="完成提醒" type="checkbox" disabled={n.scope==="common"&&!p?.manage} checked={n.done} onChange={e=>setReminders(rs=>rs.map((v,j)=>i===j?{...v,done:e.target.checked}:v))}/><Input aria-label="提醒内容" disabled={n.scope==="common"&&!p?.manage} value={n.text} onChange={e=>setReminders(rs=>rs.map((v,j)=>i===j?{...v,text:e.target.value}:v))}/><span>{n.scope==="common"?"通用":"个人"}</span>{(p?.manage||n.scope===p?.memberId)&&<Button variant="ghost" onClick={()=>setReminders(rs=>rs.filter((_,j)=>j!==i))}>删除</Button>}</div>)}{p?.memberId&&<><div className="row"><Input aria-label="新提醒" placeholder="添加提醒…" value={newReminder} onChange={e=>setNewReminder(e.target.value)}/><select value={p.manage?reminderScope:p.memberId} onChange={e=>setReminderScope(e.target.value)}>{p.manage&&<option value="common">通用提醒</option>}<option value={p.memberId}>个人提醒</option></select><Button onClick={()=>{if(newReminder.trim()){setReminders([...reminders,{id:crypto.randomUUID(),text:newReminder.trim(),done:false,scope:p.manage?reminderScope:p.memberId!}]);setNewReminder("");}}}>添加</Button></div><Button disabled={busy} onClick={()=>void mutate("reminders",{reminders})}>保存提醒</Button></>}</div>}
 {dialog==="new"&&<div className="stack"><label>旅行标题<Input value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><label>目的地<Input value={newCity} onChange={e=>setNewCity(e.target.value)}/></label><label>大致月份<Input value={newMonth} onChange={e=>setNewMonth(e.target.value)}/></label><label>天数<Input type="number" min="1" max="90" value={newDays} onChange={e=>setNewDays(Number(e.target.value))}/></label><Button disabled={busy||!newTitle.trim()||newDays<1||newDays>90} onClick={()=>{const t=emptyTrip();t.title=newTitle;t.monthRange=newMonth||"日期待定";t.days=Array.from({length:newDays},(_,i)=>({no:String(i+1).padStart(2,"0"),city:newCity,title:"待安排",summary:"",stops:[]}));void create(t);}}>创建空白旅行</Button>{trip&&<Button variant="outline" disabled={busy} onClick={()=>void create({...trip,title:trip.title+" · 副本"})}>复制当前旅行（不复制账本和权限）</Button>}</div>}
 {dialog==="import"&&<div className="stack"><p>在聊天中确定路线后，上传按模板生成的 JSON。导入会创建新旅行，不会覆盖旧旅行或批准成员。</p><a href="/travel-import-template.json" download>下载模板</a><Input aria-label="上传方案 JSON" type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1_200_000)throw new Error("文件不能超过 1.2MB");setImported(parseImport(JSON.parse(await file.text())));}catch(e){setImported(null);setNotice("导入失败："+(e as Error).message);}}}/>{imported&&<div className="inset"><h3>{imported.title}</h3><p>{imported.monthRange} · {imported.days.length} 天 · {imported.days.reduce((n,d)=>n+d.stops.length,0)} 个地点</p>{imported.days.map((d,i)=><p key={i}>第 {i+1} 天：{d.city} · {d.stops.map(s=>s.title).join(" → ")}</p>)}<Button disabled={busy} onClick={()=>void create(imported)}>确认导入为新旅行</Button></div>}</div>}
 </DialogContent></Dialog>
 <Dialog open={!!stopEdit} onOpenChange={v=>{if(!v)setStopEdit(null);}}><DialogContent className="travel-dialog"><DialogHeader><DialogTitle>编辑行程地点</DialogTitle></DialogHeader>{stopEdit&&<><StopEditor stop={stopEdit.stop} onChange={stop=>setStopEdit({...stopEdit,stop})}/><Button onClick={()=>{if(!trip||!stopEdit.stop.title.trim())return;const stops=[...trip.days[stopEdit.day].stops];stops[stopEdit.index]=stopEdit.stop;changeDay(stopEdit.day,{stops});setStopEdit(null);}}>应用到行程草稿</Button></>}</DialogContent></Dialog>
 </main>;
}
