"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import type { LedgerBill,TripLedger,TripMember } from "@/lib/trip-data";
import { currencies } from "@/lib/travel-schema";
import { balances,transfers,validateLedger } from "@/lib/ledger-math";
import { receiptFile,saveFile } from "@/lib/navigation";
const cats=["美食","交通","住宿","门票","购物","其他"] as const;
const cash=(n:number,c:string)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:c}).format(n/100);
export function Ledger({ledger,members,canEdit,manager,viewerId,onSave}:{ledger:TripLedger;members:TripMember[];canEdit:boolean;manager:boolean;viewerId:string|null;onSave:(ledger:TripLedger)=>Promise<boolean>}){
 const active=members.filter(m=>!m.archived);
 const [edit,setEdit]=useState<LedgerBill|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [filter,setFilter]=useState("全部"),[person,setPerson]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const [repay,setRepay]=useState({fromId:viewerId||active[0]?.id||"",toId:active[1]?.id||"",amount:""});
 const rows=balances(members,ledger),suggestions=transfers(rows);
 const name=(id:string)=>members.find(m=>m.id===id)?.name||"历史成员";
 const displayed=ledger.bills.filter(b=>(filter==="全部"||b.category===filter)&&(!person||b.participantIds.includes(person))&&(!start||b.orderedAt>=start)&&(!end||b.orderedAt.slice(0,10)<=end));
 const sum=ledger.bills.filter(b=>!b.voided).reduce((n,b)=>n+(b.refund?-b.baseAmountCents:b.baseAmountCents),0);
 function fresh(){const now=new Date().toISOString();setEdit({id:crypto.randomUUID(),originalAmountCents:0,baseAmountCents:0,currency:ledger.baseCurrency,exchangeRate:1,category:"美食",note:"",payerId:active[0]?.id||"",participantIds:active.map(m=>m.id),orderedAt:now.slice(0,16),createdAt:now,splitMode:"equal",payments:{},splitValues:{}});}
 function patch(p:Partial<LedgerBill>){setEdit(b=>b?{...b,...p}:b);}
 async function save(l:TripLedger){setError("");setBusy(true);try{validateLedger(l,members);return await onSave(l);}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function submit(){if(!edit)return;const b={...edit,note:edit.note.trim()||edit.category+"消费",baseAmountCents:Math.round(edit.originalAmountCents*edit.exchangeRate)};const next={...ledger,bills:ledger.bills.some(v=>v.id===b.id)?ledger.bills.map(v=>v.id===b.id?b:v):[b,...ledger.bills]};if(await save(next))setEdit(null);}
 function csv(){const esc=(v:unknown)=>'"'+String(v??"").replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';saveFile("旅行账本.csv","\uFEFF"+[["日期","类别","说明","原币","金额","汇率","结算金额","付款人","参与人","状态"],...displayed.map(b=>[b.orderedAt,b.category,b.note,b.currency,b.originalAmountCents/100,b.exchangeRate,b.baseAmountCents/100,Object.keys(b.payments&&Object.keys(b.payments).length?b.payments:{[b.payerId]:1}).map(name).join(" / "),b.participantIds.map(name).join(" / "),b.voided?"作废":b.refund?"退款":"消费"])].map(row=>row.map(esc).join(",")).join("\r\n"),"text/csv;charset=utf-8");}
 return <div className="stack"><section className="travel-card"><div className="row between wrap"><div><p className="eyebrow">SHARED EXPENSES</p><h2>共同账本</h2><p className="big-number">{cash(sum,ledger.baseCurrency)}</p></div><div className="row wrap"><Button variant="outline" onClick={csv}>导出明细</Button>{canEdit&&<Button onClick={fresh}>记一笔</Button>}</div></div><label>结算币种<select disabled={!canEdit||ledger.bills.length>0||(ledger.repayments||[]).length>0} value={ledger.baseCurrency} onChange={e=>void save({...ledger,baseCurrency:e.target.value as TripLedger["baseCurrency"]})}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><p className="muted">汇率手动输入，每笔独立保存。已有账目后锁定结算币种。</p></section>
 {error&&<p role="alert" className="notice">{error}</p>}
 <section className="travel-card"><h3>按分类与成员查看</h3><div className="fields"><label>分类<select value={filter} onChange={e=>setFilter(e.target.value)}>{["全部",...cats].map(c=><option key={c}>{c}</option>)}</select></label><label>参与成员<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">全部成员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>开始日期<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束日期<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 {displayed.map(b=><article key={b.id} className="list-row"><div><strong>{b.note}</strong><p className="muted">{b.orderedAt.replace("T"," ")} · {b.category} · {b.voided?"已作废":b.refund?"退款":"消费"}</p><p>{cash(b.originalAmountCents,b.currency)} → {cash(b.baseAmountCents,ledger.baseCurrency)}</p><p className="muted">{b.participantIds.map(name).join("、")} 分摊</p>{b.receipt&&<details><summary>查看票据</summary><img src={b.receipt} alt="账单票据" className="receipt"/></details>}</div>{canEdit&&<div className="row wrap"><Button variant="outline" onClick={()=>{setError("");setEdit(structuredClone(b));}}>编辑</Button><Button variant="ghost" disabled={busy} onClick={()=>void save({...ledger,bills:ledger.bills.map(v=>v.id===b.id?{...v,voided:!v.voided}:v)})}>{b.voided?"恢复":"作废"}</Button></div>}</article>)}
 {!displayed.length&&<p className="empty">还没有符合条件的账单。</p>}
 <div className="fields">{cats.map(c=><div key={c}><span className="muted">{c}</span><p>{cash(displayed.filter(b=>b.category===c&&!b.voided).reduce((s,b)=>s+(b.refund?-1:1)*b.baseAmountCents,0),ledger.baseCurrency)}</p></div>)}</div></section>
 <section className="travel-card"><h2>结算与实际还款</h2><div className="fields">{rows.map(m=><article className="inset" key={m.id}><strong>{m.name}{m.archived?"（已离团）":""}</strong><p>已付 {cash(m.paid,ledger.baseCurrency)} · 应摊 {cash(m.owed,ledger.baseCurrency)}</p><strong>{m.net>0?"待收":m.net<0?"待付":"已结清"} {cash(Math.abs(m.net),ledger.baseCurrency)}</strong></article>)}</div><h3>转账建议</h3>{suggestions.map((t,i)=><p key={i}>{name(t.fromId)} → {name(t.toId)}：{cash(t.amount,ledger.baseCurrency)}</p>)}<p className="muted">建议不会自动记为已还款，也不会发起真实转账。</p>
 {canEdit&&<div className="fields"><label>付款人<select value={repay.fromId} onChange={e=>setRepay({...repay,fromId:e.target.value})}>{members.filter(m=>manager||m.id===viewerId).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>收款人<select value={repay.toId} onChange={e=>setRepay({...repay,toId:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>金额（{ledger.baseCurrency}）<Input type="number" min="0.01" step="0.01" value={repay.amount} onChange={e=>setRepay({...repay,amount:e.target.value})}/></label><Button disabled={busy} onClick={()=>void save({...ledger,repayments:[...(ledger.repayments||[]),{id:crypto.randomUUID(),fromId:repay.fromId,toId:repay.toId,amount:Math.round(Number(repay.amount)*100),confirmed:false,date:new Date().toISOString()}]})}>登记还款</Button></div>}
 {(ledger.repayments||[]).map(p=><div className="list-row" key={p.id}><p>{name(p.fromId)} → {name(p.toId)} · {cash(p.amount,ledger.baseCurrency)} · {p.confirmed?"已确认收款":"待收款人确认"}</p>{!p.confirmed&&canEdit&&(manager||viewerId===p.toId)&&<Button disabled={busy} onClick={()=>void save({...ledger,repayments:ledger.repayments!.map(v=>v.id===p.id?{...v,confirmed:true}:v)})}>确认收到</Button>}</div>)}</section>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null);}}><DialogContent className="travel-dialog"><DialogHeader><DialogTitle>{ledger.bills.some(b=>b.id===edit?.id)?"编辑账单":"新账单"}</DialogTitle></DialogHeader>{edit&&<div className="stack">
 <div className="fields"><label>说明<Input value={edit.note} onChange={e=>patch({note:e.target.value})}/></label><label>类别<select value={edit.category} onChange={e=>patch({category:e.target.value as LedgerBill["category"]})}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>消费日期<Input type="datetime-local" value={edit.orderedAt} onChange={e=>patch({orderedAt:e.target.value})}/></label><label>关联行程日<Input placeholder="例如 第 2 天" value={edit.day||""} onChange={e=>patch({day:e.target.value})}/></label><label>原币<select value={edit.currency} onChange={e=>patch({currency:e.target.value as LedgerBill["currency"],exchangeRate:e.target.value===ledger.baseCurrency?1:edit.exchangeRate})}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>原币金额<Input type="number" min=".01" step=".01" value={edit.originalAmountCents/100||""} onChange={e=>patch({originalAmountCents:Math.round(Number(e.target.value)*100)})}/></label><label>1 {edit.currency} = 多少 {ledger.baseCurrency}<Input type="number" min=".00000001" step="any" value={edit.exchangeRate} onChange={e=>patch({exchangeRate:Number(e.target.value)})}/></label><label>分摊方式<select value={edit.splitMode||"equal"} onChange={e=>patch({splitMode:e.target.value as LedgerBill["splitMode"]})}><option value="equal">均摊</option><option value="amount">指定原币金额</option><option value="percent">百分比</option><option value="shares">份数</option></select></label></div>
 <label className="check"><input type="checkbox" checked={!!edit.refund} onChange={e=>patch({refund:e.target.checked})}/>这是退款（冲减支出）</label>
 <p>选择参加的人，右侧填写该成员垫付的原币金额。多人付款直接分别填写。</p>
 {members.map(m=><div className="fields inset" key={m.id}><label className="check"><input type="checkbox" checked={edit.participantIds.includes(m.id)} onChange={e=>patch({participantIds:e.target.checked?[...edit.participantIds,m.id]:edit.participantIds.filter(id=>id!==m.id)})}/>{m.name}</label>{edit.splitMode!=="equal"&&edit.participantIds.includes(m.id)&&<label>{edit.splitMode==="percent"?"比例 %":edit.splitMode==="shares"?"份数":"应摊原币金额"}<Input type="number" min="0" step="any" value={edit.splitValues?.[m.id]??""} onChange={e=>patch({splitValues:{...edit.splitValues,[m.id]:Number(e.target.value)}})}/></label>}<label>垫付原币金额<Input type="number" min="0" step=".01" value={edit.payments?.[m.id]?edit.payments[m.id]/100:""} onChange={e=>patch({payments:{...edit.payments,[m.id]:Math.round(Number(e.target.value)*100)}})}/></label></div>)}
 <label>票据照片（压缩后存储）<Input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void receiptFile(f).then(receipt=>patch({receipt})).catch(e=>setError(e.message));}}/></label>{edit.receipt&&<Button variant="outline" onClick={()=>patch({receipt:undefined})}>移除票据</Button>}
 {error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={()=>void submit()}>保存账单</Button></div>}</DialogContent></Dialog></div>;
}
