"use client";
import {useState} from "react";
import type {TripMember,TripSnapshot,TravelStop} from "@/lib/trip-data";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {LiveMap} from "./live-map";
export function MembersEditor({trip,journeyId,manage,onSave}:{trip:TripSnapshot;journeyId:string;manage:boolean;onSave:(members:TripMember[])=>Promise<boolean>}){
 const [members,setMembers]=useState(()=>structuredClone(trip.members)),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [candidate,setCandidate]=useState<{member:string;account:{id:string;email:string;name:string;registeredAt:string}}|null>(null);
 function patch(id:string,p:Partial<TripMember>){setMembers(ms=>ms.map(m=>m.id===id?{...m,...p}:m));}
 async function find(m:TripMember){setBusy(true);try{const r=await fetch("/api/journeys/accounts?"+new URLSearchParams({id:journeyId,email:m.email}));const data=await r.json() as {error?:string;users:{id:string;email:string;name:string;registeredAt:string}[]};if(!r.ok)throw new Error(data.error);if(!data.users.length){setNotice("该邮箱还没有可用账号，请让朋友先注册。");return;}setCandidate({member:m.id,account:data.users[0]});}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <div className="stack"><p>当前同行 {members.filter(m=>!m.archived).length} 人。注册后仍需在这里确认账号，才会获得本次旅行的权限。</p>{members.map(m=><article className="inset stack" key={m.id}><div className="fields"><label>姓名<Input disabled={!manage} value={m.name} onChange={e=>patch(m.id,{name:e.target.value})}/></label>{manage&&<label>邮箱<Input type="email" value={m.email} onChange={e=>patch(m.id,{email:e.target.value,accountId:undefined})}/></label>}<label>加入日期<Input disabled={!manage} type="date" value={m.startDate||""} onChange={e=>patch(m.id,{startDate:e.target.value})}/></label><label>离开日期<Input disabled={!manage} type="date" value={m.endDate||""} onChange={e=>patch(m.id,{endDate:e.target.value})}/></label></div>
 {manage&&<><div className="fields"><label>旅行权限<select value={m.permission||"viewer"} onChange={e=>patch(m.id,{permission:e.target.value as TripMember["permission"]})}><option value="viewer">只读</option><option value="editor">可编辑行程</option><option value="admin">旅行管理员</option></select></label><label className="check"><input type="checkbox" checked={m.ledgerAccess} onChange={e=>patch(m.id,{ledgerAccess:e.target.checked})}/>允许记账与分账</label></div><div className="row wrap"><Button variant="outline" disabled={busy||!m.email||!!m.archived} onClick={()=>void find(m)}>{m.accountId?"重新确认账号":"查找并审批账号"}</Button>{m.accountId&&<Button variant="ghost" onClick={()=>patch(m.id,{accountId:undefined})}>撤销访问</Button>}<Button variant="ghost" onClick={()=>patch(m.id,{archived:!m.archived,accountId:undefined})}>{m.archived?"恢复同行":"移出同行"}</Button></div></>}
 <p className="muted">{m.archived?"已离团，保留历史账目":m.accountId?"账号已绑定，保存后生效":"尚未绑定账号"}</p></article>)}
 {manage&&<div className="row wrap"><Button variant="outline" onClick={()=>setMembers([...members,{id:crypto.randomUUID(),name:"新同行人",email:"",color:"#0071e3",ledgerAccess:true,permission:"viewer"}])}>添加同行人</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{if(await onSave(members))setNotice("成员已保存。");}finally{setBusy(false);}}}>保存成员和权限</Button></div>}
 {notice&&<p role="status">{notice}</p>}
 <Dialog open={!!candidate} onOpenChange={v=>{if(!v)setCandidate(null);}}><DialogContent><DialogHeader><DialogTitle>确认这是你认识的朋友</DialogTitle></DialogHeader><p>{candidate?.account.name} · {candidate?.account.email}</p><p>注册于 {candidate?.account.registeredAt}。请与朋友核对后批准。</p><Button onClick={()=>{if(candidate)patch(candidate.member,{accountId:candidate.account.id});setCandidate(null);}}>确认绑定，随后保存成员</Button></DialogContent></Dialog></div>;
}
export function StopEditor({stop,onChange}:{stop:TravelStop;onChange:(stop:TravelStop)=>void}){
 const [query,setQuery]=useState(stop.title),[searching,setSearching]=useState(false),[notice,setNotice]=useState("");
 const [places,setPlaces]=useState<{name:string;address:string;sourceUrl:string;location:{lat:number;lng:number}}[]>([]);
 const patch=(p:Partial<TravelStop>)=>onChange({...stop,...p});
 async function search(){setSearching(true);setNotice("");try{const r=await fetch("/api/places?q="+encodeURIComponent(query));const d=await r.json() as {error?:string;places:{name:string;address:string;sourceUrl:string;location:{lat:number;lng:number}}[]};if(!r.ok)throw new Error(d.error);setPlaces(d.places);if(!d.places.length)setNotice("未找到，请填写当地名称和城市，或在地图上选点。");}catch(e){setNotice((e as Error).message);}finally{setTimeout(()=>setSearching(false),1200);}}
 return <div className="stack"><div className="row"><Input aria-label="搜索地点" value={query} placeholder="地点 + 城市 + 国家" onChange={e=>setQuery(e.target.value)}/><Button disabled={searching} onClick={()=>void search()}>搜索地点</Button></div>{notice&&<p>{notice}</p>}{places.map((p,i)=><button className="inset text-left" key={i} onClick={()=>{patch({location:p.location,nativeName:p.name,address:p.address,sourceUrl:p.sourceUrl,verifiedAt:""});setPlaces([]);}}><strong>{p.name}</strong><p>{p.address}</p></button>)}
 <div className="fields"><label>中文显示名称<Input value={stop.title} onChange={e=>patch({title:e.target.value})}/></label><label>当地名称（非自动翻译）<Input value={stop.nativeName||""} onChange={e=>patch({nativeName:e.target.value,verifiedAt:""})}/></label><label>时间<Input value={stop.time} onChange={e=>patch({time:e.target.value})}/></label><label>停留分钟<Input type="number" min="0" value={stop.durationMinutes??""} onChange={e=>patch({durationMinutes:Number(e.target.value)})}/></label><label>分类<select value={stop.kind} onChange={e=>patch({kind:e.target.value as TravelStop["kind"]})}>{["文化","风景","美食","购物","交通","经典场景"].map(k=><option key={k}>{k}</option>)}</select></label><label>开放时间<Input value={stop.openingHours||""} onChange={e=>patch({openingHours:e.target.value})}/></label></div>
 <label>当地文字地址<Input value={stop.address||""} onChange={e=>patch({address:e.target.value,verifiedAt:""})}/></label><label>资料来源链接<Input type="url" value={stop.sourceUrl||""} onChange={e=>patch({sourceUrl:e.target.value,verifiedAt:""})}/></label><label className="check"><input type="checkbox" checked={!!stop.verifiedAt} disabled={!stop.nativeName||!stop.sourceUrl} onChange={e=>patch({verifiedAt:e.target.checked?new Date().toISOString().slice(0,10):""})}/>已对照资料来源核实当地名称和地址</label>
 <div className="fields"><label>纬度<Input type="number" min="-85" max="85" step="any" value={stop.location?.lat??""} onChange={e=>patch({location:{lat:Number(e.target.value),lng:stop.location?.lng??0}})}/></label><label>经度<Input type="number" min="-180" max="180" step="any" value={stop.location?.lng??""} onChange={e=>patch({location:{lng:Number(e.target.value),lat:stop.location?.lat??0}})}/></label></div>
 <p className="muted">地点搜索：Photon · 数据 © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>。请核对搜索结果后选用。</p>
 <details><summary>在真实地图上选点</summary><LiveMap days={[{no:"1",city:"",title:"",summary:"",stops:[stop]}]} onPick={location=>patch({location})}/></details>
 <label>上一站交通方式与预计用时<Input value={stop.transportFromPrevious||""} onChange={e=>patch({transportFromPrevious:e.target.value})}/></label><label>备注／备选安排<Textarea value={stop.note} onChange={e=>patch({note:e.target.value})}/></label><label className="check"><input type="checkbox" checked={!!stop.ticketRequired} onChange={e=>patch({ticketRequired:e.target.checked})}/>需要购票或预约</label>{stop.ticketRequired&&<label>预约说明<Input value={stop.ticketNote||""} onChange={e=>patch({ticketNote:e.target.value})}/></label>}</div>;
}
