import type { TripSnapshot,TravelDay } from "./trip-data";
import { googleUrl,amapUrl,saveFile } from "./navigation";
import { balances } from "./ledger-math";
const esc=(v:unknown)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
function routeSvg(days:TravelDay[]){
 const pts=days.flatMap(d=>d.stops).filter(s=>s.location);if(!pts.length)return "<p>未填写地点坐标</p>";
 const xs=pts.map(s=>s.location!.lng),ys=pts.map(s=>-Math.log(Math.tan(Math.PI/4+s.location!.lat*Math.PI/360)));
 const minX=Math.min(...xs),minY=Math.min(...ys),dx=Math.max(.005,Math.max(...xs)-minX),dy=Math.max(.0001,Math.max(...ys)-minY);
 const points=pts.map((s,i)=>({x:35+530*(xs[i]-minX)/dx,y:30+220*(ys[i]-minY)/dy}));
 return '<svg viewBox="0 0 600 285" role="img" aria-label="按真实坐标投影的路线示意"><rect width="600" height="285" fill="#edf4fb"/><polyline fill="none" stroke="#0071e3" stroke-width="2" points="'+points.map(p=>p.x+","+p.y).join(" ")+'"/>'+points.map((p,i)=>'<circle cx="'+p.x+'" cy="'+p.y+'" r="11" fill="#143958"/><text x="'+p.x+'" y="'+(p.y+4)+'" text-anchor="middle" font-size="10" fill="white">'+(i+1)+'</text>').join("")+'</svg><p>路线示意，无离线街道底图；数字对应下列地点顺序。</p>';
}
export function guideHtml(t:TripSnapshot){
 const names=(ids?:string[])=>ids?.map(id=>t.members.find(m=>m.id===id)?.name||"历史成员").join("、")||"未指定";
 const billRows=t.ledger.bills.map(b=>'<tr><td>'+esc(b.orderedAt)+'</td><td>'+esc(b.category+" / "+b.note)+'</td><td>'+esc(b.currency+" "+b.originalAmountCents/100)+'</td><td>'+esc(b.exchangeRate)+'</td><td>'+esc(t.ledger.baseCurrency+" "+b.baseAmountCents/100)+'</td><td>'+esc(names(b.participantIds))+'</td><td>'+esc(b.voided?"作废":b.refund?"退款":"消费")+'</td></tr>').join("");
 return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(t.title)+'</title><style>body{font:16px/1.7 system-ui,sans-serif;color:#172536;background:#f4f6f8;margin:0}main{max-width:900px;margin:auto;padding:24px}section,article{background:white;padding:20px;margin:16px 0;border-radius:16px;break-inside:avoid}h1{font-size:36px}h2{border-bottom:1px solid #ddd;padding-bottom:8px}p,li,td{overflow-wrap:anywhere;white-space:pre-wrap}a{color:#0069c8}nav{display:flex;flex-wrap:wrap;gap:12px}svg{width:100%;max-height:350px}img{max-width:100%;max-height:400px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:8px;border:1px solid #ddd}button{padding:12px;border:0;border-radius:10px} @media print{body{background:white}main{padding:0}button{display:none}section,article{padding:8px}a{color:inherit}table{font-size:10px}@page{size:A4;margin:14mm}</style></head><body><main><button onclick="window.print()">打印 / 保存 PDF</button><h1>'+esc(t.title)+'</h1><p>'+esc((t.exactStart||t.monthRange)+" — "+t.exactEnd)+' · '+t.members.filter(m=>!m.archived).length+' 人</p><p>导出于 '+esc(new Date().toLocaleString("zh-CN"))+'。这是离线快照，导航链接需联网。</p><nav>'+t.days.map((d,i)=>'<a href="#day'+i+'">第 '+(i+1)+' 天</a>').join("")+'</nav><section><h2>整段路线</h2>'+routeSvg(t.days)+'</section><section><h2>交通与乘机信息</h2>'+t.transports.map(v=>'<article><h3>'+esc(v.type+" · "+v.service)+'</h3><p>'+esc(v.from+" → "+v.to)+'</p><p>'+esc(v.date+" "+(v.departureTimezone||"")+" → "+(v.arrival||"")+" "+(v.arrivalTimezone||""))+'</p><p>'+esc("航站楼："+(v.terminal||"")+" / 座位："+(v.seat||"")+" / 行李："+(v.baggage||""))+'</p><p>'+esc(names(v.memberIds))+'</p><p>'+esc(v.detail)+'</p>'+(v.attachment?'<img alt="交通附件" src="'+esc(v.attachment)+'">':"")+'</article>').join("")+'</section>'+
 t.days.map((d,i)=>'<section id="day'+i+'"><h2>第 '+(i+1)+' 天 · '+esc(d.city+" "+d.title)+'</h2><p>'+esc(d.summary)+'</p>'+routeSvg([d])+d.stops.map((s,j)=>'<article><h3>'+(j+1)+'. '+esc(s.time+" "+s.title)+'</h3><p>'+esc((s.nativeName||"当地名称待核实")+"\n"+(s.address||""))+'</p><p>'+esc(s.note)+'</p><p>'+esc("开放时间："+(s.openingHours||"待核实")+" / 停留："+(s.durationMinutes??"待定")+" 分钟")+'</p><p>'+esc(s.transportFromPrevious||"")+'</p>'+(s.ticketRequired?'<p>'+esc((s.ticketDone?"☑ 已购票／预约":"☐ 待购票／预约")+" "+(s.ticketNote||""))+'</p>':"")+'<a href="'+esc(googleUrl(s))+'">Google 地图</a> · <a href="'+esc(amapUrl(s))+'">高德地图</a>'+(s.sourceUrl&&/^https?:\/\//i.test(s.sourceUrl)?' · <a href="'+esc(s.sourceUrl)+'">资料来源</a>':"")+'</article>').join("")+'</section>').join("")+
 '<section><h2>出发前提醒</h2>'+t.preTripReminders.map(n=>'<p>'+esc((n.done?"☑ ":"☐ ")+(n.scope==="common"?"[通用] ":"[个人] ")+n.text)+'</p>').join("")+'</section><section><h2>注意事项</h2><p>'+esc(t.notes)+'</p></section><section><h2>共同账本</h2><table><thead><tr><th>日期</th><th>说明</th><th>原币金额</th><th>汇率</th><th>结算金额</th><th>参与人</th><th>状态</th></tr></thead><tbody>'+billRows+'</tbody></table>'+balances(t.members,t.ledger).map(m=>'<p>'+esc(m.name+"："+(m.net>=0?"待收 ":"待付 ")+Math.abs(m.net)/100+" "+t.ledger.baseCurrency)+'</p>').join("")+(t.ledger.repayments||[]).map(p=>'<p>'+esc(names([p.fromId])+" → "+names([p.toId])+" "+p.amount/100+" "+t.ledger.baseCurrency+" "+(p.confirmed?"已确认":"待确认"))+'</p>').join("")+t.ledger.bills.filter(b=>b.receipt).map(b=>'<article><p>'+esc(b.note)+'</p><img alt="票据" src="'+esc(b.receipt)+'"></article>').join("")+'</section></main></body></html>';
}
export function downloadGuide(t:TripSnapshot){saveFile(t.title+".html",guideHtml(t),"text/html;charset=utf-8");}
export function printGuide(t:TripSnapshot){const w=window.open("","_blank");if(!w)throw new Error("请允许弹出打印窗口，或下载 HTML 后打开打印");w.document.open();w.onload=()=>w.print();w.document.write(guideHtml(t));w.document.close();}
